services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.3.0
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  # app:
  #   build: .
  #   tty: true
  #   volumes:
  #     - .:/myapp/

  awscli:
    image: amazon/aws-cli:2.15.36
    entrypoint: "bash"
    volumes:
      - "./.aws:/root/.aws"
      - "./resources:/aws/resources/"
    tty: true
